import PACKET from './PacketStructure';
export default {
	0x69: PACKET.AC.ACCEPT_LOGIN,
	0x6a: PACKET.AC.REFUSE_LOGIN,
	0x6b: PACKET.HC.ACCEPT_ENTER_NEO_UNION, 
	0x6c: PACKET.HC.REFUSE_ENTER, 
	0x6e: PACKET.HC.REFUSE_MAKECHAR,
	0x71: PACKET.HC.NOTIFY_ZONESVR,
	0x81: PACKET.SC.NOTIFY_BAN,
	0x20d: PACKET.HC.BLOCK_CHARACTER,
	0xb6f: PACKET.HC.ACCEPT_MAKECHAR,
	0x82d: PACKET.HC.ACCEPT_ENTER_NEO_UNION_HEADER, 
	0x8b9: PACKET.HC.SECOND_PASSWD_LOGIN, // ok
	0x9a0: PACKET.HC.CHARLIST_NOTIFY,
	
};
